//Objective:  template for C++ programs and to test code
//Name: Luis Cermeno-Farro 1837034
//Course: COMSC-110-8076
//Compiler: Xcode
//Editor: TextEdit

//libraries
#include <fstream>
#include <iostream>
using namespace std;

#include <cstdlib>
#include <ctime>

//Programmer defined data types
//NONE

//Special compiler dependent definitions
//NONE

//global constants/variables
//NONE

//Programmer defined functions
void introduction(string obj);//user introduction
void readFile(); //function to create or read file and get lastScore
int userInput(int target); //function to ask for user input and output feedback
void overwriteFile(int i); //function to overwritefile with user Score

//main program
int main()
{
  //User introduction
  string objective = "Ask the user to guess a number between 1 and 100.";
  introduction(objective);
  
  //Data initialization and generation of a ramdom number between 1 and 100
  srand(time(0)); //"seed the ramdom number generator"
  int target = 1 + rand() % 100; // (integer) a ramdom number from 1 to 100 generated by the computer 
  int i; //(integer)number of attemps the user has made.

  //Read file and output last score
  readFile();

  //Game loop where the user guesses and gets feedback.
  i = userInput(target);

  //Save the user score in text file
  overwriteFile(i);
}//main



//introduction function
void introduction(string obj)//user introduction
{
  //data
  //obj is the program objective

  //introduction
  cout << obj; 
  cout << "Programmer: Luis Cermeno-Farro\n"; 
  cout << "Editor(s) used: TextEdit\n"; 
  cout << "Compiler(s) used: Xcode\n"; 
  cout << "File: " << __FILE__ << endl; 
  cout << "Complied: " << __DATE__ << " at " << __TIME__ << endl << endl; 

}//introduction function

//function to create or read file and get lastScore
void readFile()
{
  //data
  int lastScore; //(integer): number of guesses the last user took to guess the correct number
  //creates the file in case it didnt previously exist
  ofstream fout;
  
  //read the file
  ifstream fin;
  fin.open("scores.txt");
  if (!(fin.good()))
  {
    fout.open("scores.txt");
    fout.close();
    fout.clear();
  }
  fin >> lastScore;
  fin.ignore(1000,10);

  //output last score
  if (lastScore > 0 && lastScore < 1000) cout << "Last player took " << lastScore << " guesses to guess the correct number" << endl;
  else cout << "No player has played the game yet, you are the first one good luck!." << endl;
  fin.close();
}//function to read file and get lastScore

//function to ask for user input and output feedback
int userInput(int target)
{
  //data
  int userGuess; //(integer) number guessed each time by the user.
  int i = 0; //(integer): counter for the main loop of the program, saves the number of guess the user is taking.

  //main loop to promt the user
  cout << "I'm thinking of a number from 1 to 100. Guess what it is [1-100 or 0 to Exit]:";
  while (true)
  {
   i++;
   cin >> userGuess;
   cin.ignore(1000,10);

   if (userGuess < 1 || userGuess > 100)
   {
    cout << "Invalid input--guess again:";
    i--;
    continue;
   }//if invalid guess

   else if (userGuess > target)
   {
    cout << "That's too high--guess again:";
    continue;
   }//if guess is too high

   else if (userGuess < target)
   {
    cout << "That's too low--guess again:";
    continue;
   }//if guess is too low

   else if(userGuess == target)
   {
    cout << "That's right--it's " << target << endl;
    break;
   }
  }//while true loop
  return i;
}//function to ask for user input and output feedback

//function to overwritefile with user Score
void overwriteFile(int i)
{
  ofstream fout;
  fout.open("scores.txt");
  if (!(fout.good())) throw "I/O error";
  fout << i;
  fout.close();
}//function to overwritefile with user Score
