//Objective:  template for C++ programs and to test code
//Name: Luis Cermeno-Farro 1837034
//Course: COMSC-110-8076
//Compiler: TDM MinGW
//Editor: MS NotePad

//libraries
#include <iostream>
using namespace std;

#include <cstdlib>
#include <ctime>

//Programmer defined data types
//NONE

//Special compiler dependent definitions
//NONE

//global constants/variables
//NONE

//Programmer defined functions
//NONE

//main program
int main()
{
  //Data and generation of a ramdom number between 1 and 10
  srand(time(0)); //"seed the ramdom number generator" ALWAYS AS FIRST STATEMENT IN MAIN
  int target = 1 + rand() % 10; // (integer) a ramdom number from 1 to 10 generated by the computer 
  int userGuess; //(integer) number guessed each time by the user.


  // Introduction
  cout << "Objective: Ask the user to guess a number between 1 and 10.\n"; 
  cout << "Programmer: Luis Cermeno-Farro\n"; 
  cout << "Editor(s) used: Notepad\n"; 
  cout << "Compiler(s) used: TDM MinGW\n"; 
  cout << "File: " << __FILE__ << endl; 
  cout << "Complied: " << __DATE__ << " at " << __TIME__ << endl << endl; 

  // Game loop where either the user guesses and gets feedback, or exits the game.
  while (true)
  {
   cout << "What is your guess [1-10 or 0 to Exit]?";
   cin >> userGuess;
   cin.ignore(1000,10);
   if (userGuess == 0) break;
   else if (userGuess < 1 || userGuess > 10)
   {
    cout << "I really want a number between 1 and 10." << endl;
   }//if invalid guess
   else if(userGuess == target)
   {
    cout << "You guessed it!" << endl;
    break;
   }
   else
   {
    cout << "Try again..." << endl;
   }//if userGess is 0

  }//while true loop
}//main