//Objective:  template for C++ programs and to test code
//Name: Luis Cermeno-Farro 1837034
//Course: COMSC-110-8076
//Compiler: Xcode
//Editor: TextEdit

//libraries
#include <iostream>
using namespace std;

#include <cstdlib>
#include <ctime>

//Programmer defined data types
//NONE

//Special compiler dependent definitions
//NONE

//global constants/variables
//NONE

//Programmer defined functions
void introduction(string obj);//user introduction
int computerPlay_func();//computer play
int userPlay_func();//user play
void decision_func(char computer,char user,int computerWins,int userWins);//determine winner and keep score

//main program
int main()
{
  //Data
  string objective = "Display an interactive rock-paper-scissors game human vs. computer..\n";
  char userPlay; //(character) the user's choice between rock,paper,scissors.
  int computerPlay; //(integer) the computer random choice (0-rock, 1-paper, 2-scissors).
  int userScore = 0; //(integer) the number of user wins
  int computerScore = 0; //(integer) the number of computer wins

  //User introduction
  introduction(objective);

  //Generation of a random number and user input
  while (true)
  {
    computerPlay = computerPlay_func(); 
    userPlay = userPlay_func();
    if (toupper(userPlay) == 'Q') break;
    else if (toupper(userPlay) != 'R' && toupper(userPlay) != 'P' && toupper(userPlay) != 'S')
    {
      cout << "Invalid input,try again..." << endl << endl;
      continue;
    }
    //Winner decision and scoreboard
    decision_func(computerPlay,userPlay,computerScore,userScore); 
  }
  cout << endl << "Thanks for playing!" << endl;

}//main



//function: introduction
void introduction(string obj)//user introduction
{
  //Data
  //obj is the program objective
  //introduction
  cout << obj; 
  cout << "Programmer: Luis Cermeno-Farro\n"; 
  cout << "Editor(s) used: TextEdit\n"; 
  cout << "Compiler(s) used: Xcode\n"; 
  cout << "File: " << __FILE__ << endl; 
  cout << "Complied: " << __DATE__ << " at " << __TIME__ << endl << endl;
  cout << "Welcome to the game of Rock, Paper, Scissors. You will be asked to choose either R=rock or P=paper or S=scissors, and the computer will do the same. The winner is determined by Rock wins against Scissors, or Scissors wins against Paper, or Paper wins against Rock. The game winner is the player with the most scores. The best player is the player with the highest overall score." << endl << endl ; 

}//function: introduction



//function: computerPlay
int computerPlay_func()
{
  //Data
  int result = 0;
  //Generation of random number
  srand(time(0)); //"seed the ramdom number generator"
  result = rand() % 3; // assignment of the ramdom number from 0 to 2 generated by the computer
  return result;
}//function: computerPlay



//function: userPlay
int userPlay_func()
{
  //Data
  char result;
  //Prompt and store the value input
  cout << "Choose [R=rock, P=paper, S=scissors, or Q=quit]: ";
  cin >> result;  
  cin.ignore(1000,10);
  return result;
}//function: userPlay



//function: decision and scoreboard
void decision_func(char computer,char user,int computerWins,int userWins)
{
  if (toupper(user) == 'R' && computer == 0)
  {
    cout << "Computer: R, Human: " << user << ",tie" << endl;
    cout << "Computer wins: " << computerWins << " Human wins: " << userWins << endl << endl;
  }
  else if (toupper(user) == 'R' && computer == 1)
  {
    cout << "Computer: P, Human: " << user << ",Computer wins" << endl;
    computerWins = computerWins + 1;
    cout << "Computer wins: " << computerWins << " Human wins: " << userWins << endl << endl;
  }
  else if (toupper(user) == 'R' && computer == 2)
  {
    cout << "Computer: S, Human: " << user << ",you win!" << endl;
    userWins = userWins + 1;
    cout << "Computer wins: " << computerWins << " Human wins: " << userWins << endl << endl;
  }
  else if (toupper(user) == 'P' && computer == 0)
  {
    cout << "Computer: R, Human: " << user << ",you win!" << endl;
    userWins = userWins + 1;
    cout << "Computer wins: " << computerWins << " Human wins: " << userWins << endl << endl;
  }
  else if (toupper(user) == 'P' && computer == 1)
  {
    cout << "Computer: P, Human: " << user << ",tie" << endl;
    cout << "Computer wins: " << computerWins << " Human wins: " << userWins << endl << endl;
  }
  else if (toupper(user) == 'P' && computer == 2)
  {
    cout << "Computer: S, Human: " << user << ",Computer wins" << endl;
    computerWins = computerWins + 1;
    cout << "Computer wins: " << computerWins << " Human wins: " << userWins << endl << endl;
  }
  else if (toupper(user) == 'S' && computer == 0)
  {
    cout << "Computer: R, Human: " << user << ",Computer wins" << endl;
    computerWins = computerWins + 1;
    cout << "Computer wins: " << computerWins << " Human wins: " << userWins << endl << endl;
  }
  else if (toupper(user) == 'S' && computer == 1)
  {
    cout << "Computer: P, Human: " << user << ",you win!" << endl;
    userWins = userWins + 1;
    cout << "Computer wins: " << computerWins << " Human wins: " << userWins << endl << endl;
  }
  else if (toupper(user) == 'S' && computer == 2)
  {
    cout << "Computer: S, Human: " << user << ",tie" << endl;
    cout << "Computer wins: " << computerWins << " Human wins: "<< userWins << endl << endl;
  }
}//function: decision and scoreboard